### ISSUE TITLE
Media type no longer requires API version

### ISSUE THREAD

**Issue by chungyc** [brandonchinn178/github-rest#32]
## Describe the bug

The documentation for `apiVersion` in [`GitHubSettings`](https://hackage.haskell.org/package/github-rest-1.1.2/docs/GitHub-REST.html#t:GitHubSettings) has this note:

> The media type will be sent as: application/vnd.github.VERSION+json. For the standard API endpoints, "v3" should be sufficient here. See https://developer.github.com/v3/media/

However, this is no longer required, and in fact will be ignored, according to [REST API / Overview / Media types](https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28):

> Note: In the past, we recommended including v3 in your Accept header. This is no longer required and will have no impact on your API requests.

## Expected behavior

The note should be updated.  The relevant code should also be modified such that passing in an empty string for `apiVersion` would result in `application/vnd.github+json` and not `application/vnd.github.+json`.

It would also be nice to be able to remove the field entirely, but likely not practical for the foreseeable future for backwards compatibility.

**Comment by brandonchinn178** [comment]
Looks like the version is now stored in the `X-GitHub-Api-Version` header. We should still enable setting a version for that. We should probably also add `defaultSettings`
